baseURL: /
languageCode: en-us
title: Lift theme
theme: lift
author:
  name: Airship
  homepage: https://airshipwebsites.com

summaryLength: 70

menu:
  # Main menu
  main:
  - name: Home
    pageRef: /
    weight: 10
    params:
      class: home
  - name: Services
    pageRef: /services
    weight: 20
  - name: Service 1
    parent: Services
    pageRef: /services/service-1
    weight: 1
  - name: Service 2
    parent: Services
    pageRef: /services/service-2
    weight: 2    
  - name: About
    pageRef: /about
    weight: 30
  - name: Contact
    pageRef: /contact
    weight: 40
  # Footer menu
  footer:
  - name: Home
    pageRef: /
    weight: 10
  - name: Services
    pageRef: /services
    weight: 20
  - name: Service 1
    parent: Services
    pageRef: /services/service-1
    weight: 1
  - name: Service 2
    parent: Services
    pageRef: /services/service-2
    weight: 2
  - name: About
    pageRef: /about
    weight: 30
  - name: Contact
    pageRef: /contact
    weight: 40

params:
  # Google Tag Manager ID
  gtm: GTM-XXXXXXXX
  # DEFAULTS
  # Description for HEAD tags
  description: Starter theme for small business websites.
  # The text used for "More" buttons/links
  more_text: More
  # Header background image path
  header_image: images/header.jpg
  # Footer background image path
  footer_image: images/footer.jpg
